service: skore-clam-antivirus

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObjectTagging
      Resource: "arn:aws:s3:::skore-clam-antivirus/*"

functions:
  virusScan:
    handler: handler.virusScan
    memorySize: 2048
    events:
      - s3: 
          bucket: skore-clam-antivirus
          event: s3:ObjectCreated:*
    layers:
      - clamav
    timeout: 120

package:
  exclude:
    - node_modules/**
    - coverage/**

layers:
  clamav:
    path: layer
